version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./src/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    networks:
      - iris-net

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - iris-net

networks:
  iris-net:
