# Base image
FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Build React app
RUN npm run build

# Use a tiny server for static files
RUN npm install -g serve
EXPOSE 3000

CMD ["serve", "-s", "dist"]
